### ISSUE TITLE
[ENHANCEMENT] Add continuous integration setting

### ISSUE THREAD

**Issue by setiadijoe** [sapawarga/userpost-service#12]
## Tasks
1. [ ] add webhook on the repository from code-climate
2. [ ] create directory `.github.com/workflows` and add file `ci.yml`
3. [ ] add badges for go report card, maintainability, test coverage
