### ISSUE TITLE
[ENHANCEMENT] Add unit test for testcase

### ISSUE THREAD

**Issue by setiadijoe** [sapawarga/userpost-service#3]
## Issue
For every method on usecase package, must have unit test
## Task
- [x] unit test Get List User Post
- [x] unit test Get Detail User Post
- [x] unit test Create New User Post
- [x] unit test Liked a post
- [x] unit test Get User Post by me
- [x] unit test Update a post
- [x] unit test Add New Comment
- [x] unit test Get List Comment on a Post
