### ISSUE TITLE
[ENHANCEMENT] Create query in repository package

### ISSUE THREAD

**Issue by setiadijoe** [sapawarga/userpost-service#33]
## Tasks
Create query implementation from repository interface
- [x] Get list post
- [x] Get list post by me
- [x] Get metadata post
- [x] Get metadata post by me
- [x] Get actor
- [x] Get is liked by user
- [x] Get detail post
- [x] Insert post
- [x] Update status or title
- [x] Get last comment
- [x] Get total comments
- [x] Get comment by post id
- [x] Create
