### ISSUE TITLE
[NEW Features] Create transport http handler

### ISSUE THREAD

**Issue by setiadijoe** [sapawarga/userpost-service#41]
## Issue
User can access service by protocol http

## Tasks
- [x] add http handler transport
- [x] update package cmd for running http handler
- [x] update dockerfile and docker-compose file for expose port http
