### ISSUE TITLE
[BUGFIX] Comment on user post add to post section

### ISSUE THREAD

**Issue by setiadijoe** [sapawarga/userpost-service#53]
## Issue
When user fetch detail of a post, cannot view total comments and last comment has been inserted

## Tasks
- [x] add method for return last inserted id of comment
- [x] save last insert id into post section
- [x] update comments count on post section
