### ISSUE TITLE
[BUGFIX] Issue on get list

### ISSUE THREAD

**Issue by setiadijoe** [sapawarga/userpost-service#64]
## Issue
Client cannot use filter and sorting in get list

## What should the behavior?
- Client should get list with filter by `text`, `name`, `tags` and `status`
- Client should get list and ordering by what client need

## Tasks
- [x] update query get list
- [x] update body request for get list

**Comment by setiadijoe** [comment]
- [ ] add filter `kabkota_id`. It is for get list post wherever actor's location who created the post
